services:
  api:
    build: ./api_app
    restart: always
    ports:
      - "5454"
    networks:
      - my-network

  bot:
    build: ./bot
    restart: always
    ports:
      - "5000"
    depends_on:
      - api

    networks:
      - my-network

volumes:
  web_data:

networks:
  my-network:
    driver: bridge