services:
  web:
    build: ./api_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - python_app

  python_app:
    build: ./bot
    restart: always
    ports:
      - "5050:5050"

volumes:
  web_data: