

services:


  api:
    build:
      context: ./backend

    restart: always

    networks:
      - my-network
      

  
  front:
    build:
      context: ./frontend

    restart: always

    networks:
      - my-network

    ports:
      - 5454:5454

  bot:
    build:
      context: ./bot
    restart: always
    networks:
      - my-network


      


networks:
  my-network:
