services:
  nginx:
    image: nginx:stable-alpine
    ports:
      -"80:80"
    volumes:
      -'./nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - api
      - front
    networks:
      - my-network
  api:
    build:
      context: ./backend
    restart: always
    ports:
      - "3000"
    networks:
      - my-network
      
  front:
    build:
      context: ./frontend
    restart: always
    networks:
      - my-network
    ports:
      - "8000"
      


networks:
  my-network: