services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - front
    networks:
      - my-network


  api:
    build:
      context: ./backend
    restart: always

    networks:
      - my-network


      
  front:
    build:
      context: ./frontend
    restart: always
    networks:
      - my-network

      


networks:
  my-network: